name: CI
on:
  push:
    branches: ["main", "continous-integration"]
  pull_request:
    branches: ["main"]
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  runTest:
    env:
        USEREMAIL: ${{ secrets.USEREMAIL }}
        USERPASSWORD: ${{ secrets.USERPASSWORD }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    runs-on: ubuntu-latest
    steps:
      - name: secrets
        run: echo "secret exist ${{ env.USEREMAIL }} with password ${{ env.USERPASSWORD }}"
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.17.0"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci --no-fund --no-audit
      - name: Run Tests
        run: |
          npx wdio wdio.conf.local.ts
      - uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./reports/allure/allure-report
