name: test on demand BrowserStack

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "select option"
        required: true
        default: chrome and firefox
        type: choice
        options:
          - chrome and firefox
      suite:
        description: "select suite to run"
        required: false
        type: choice
        options:
          - regression
          - smoke
      artifacts:
        description: "Allure report"
        required: false
        type: boolean

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  runTest:
    env:
        USEREMAIL: ${{ secrets.USEREMAIL }}
        USERPASSWORD: ${{ secrets.USERPASSWORD }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        BROWSERSTACK_USERNAME : ${{secrets.BROWSERSTACK_USERNAME}}
        BROWSERSTACK_ACCESS_KEY : ${{secrets.BROWSERSTACK_ACCESS_KEY}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.17.0"
          cache: "npm"
      - name: Install
        run: npm ci --no-fund --no-audit
      - if: ${{ github.event.inputs.suite == 'smoke' }}
        name: Test
        run: npx wdio wdio.conf.bstack.ts --browser ${{ github.event.inputs.browser }} --mochaOpts.grep ${{ github.event.inputs.suite }}
      - if: ${{ github.event.inputs.suite && github.event.inputs.suite != 'smoke'}}
        name: Test
        run: npx wdio wdio.conf.bstack.ts --browser ${{ github.event.inputs.browser }} --suite ${{ github.event.inputs.suite || 'regression' }}
      - if: ${{! github.event.inputs.suite }}
        name: Test
        run: npx wdio wdio.conf.bstack.ts --browser ${{ github.event.inputs.browser }}
      - if: github.event.inputs.artifacts == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./reports/allure/allure-report
